version: '2'

services:

  web:
    container_name: 'aspnetcoreapp'
    image: 'aspnetcoreapp'
    build:
      context: .
      dockerfile: aspnetcore.production.dockerfile
    volumes:
      - .:/var/www/aspnetcoreapp
    ports:
     - "80:80"
    depends_on:
     - "sqlserverlinux"
    networks:
      - aspnetcoreapp-network

  sqlserverlinux:
    container_name: 'sqlserverlinux'
    ports:
      - "1433:1433"
    image: microsoft/mssql-server-linux
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password123
    networks:
      - aspnetcoreapp-network

networks:
  aspnetcoreapp-network:
    driver: bridge


